name: event_app
description: LegendSumeet App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  flutter_svg:
  curved_navigation_bar: ^1.0.3
  table_calendar: ^3.0.9
  geolocator: ^10.1.0
  card_swiper: ^3.0.1
  geocoding: ^2.1.1
  country_picker: ^2.0.24
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
